# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: EMNLP SSLL 2022
email: sherryw@cs.cmu.edu
description: >- # this means to ignore newlines until "baseurl:"
  The webpage for the SSLL workshop at EMNLP 2022.
baseurl: "/" # the subpath of your site, e.g. /blog
#baseurl: "/~wtshuang" # the subpath of your site, e.g. /blog
#url: "https://homes.cs.washington.edu" # the base hostname & protocol for your site, e.g. http://example.com
domain: ssll-emnlp.github.io # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://ssll-emnlp.github.io # the base hostname and protocol for your site, e.g. http://example.com

logo: /assets/logo.png

# group related content like members of a team or talks at a conference.
collections:
  pubs:
    output: false

#collections:
#  pubs:
#    output: true
#    permalink: /publications.html

# set the default values
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "Sherry_Wu_CV.html"
    values:
      pdf: true

sass:
  style: compressed
  sass_dir: _sass

# Build settings
markdown: kramdown

# use everything in Gemfile
#plugins:
#  - jekyll-sitemap
#  - jekyll-feed
#  - jekyll-seo-tag
#  - jekyll-mentions
#  - jekyll-redirect-from
# Dates are used to sort publications, and we will likely upload

# publications before their conferences occur.
future: true
#safe: true
# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - backup/*
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
